# Generated by Django 4.2.19 on 2025-04-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs', to='gestion.laboratoire', verbose_name='Laboratoire'),
        ),
    ]
