# Generated by Django 4.2.19 on 2025-04-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_status'),
        ('gestion', '0003_pc_laboratoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='memoire_ram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mémoire RAM'),
        ),
        migrations.AddField(
            model_name='salle',
            name='modele_postes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modèle des postes'),
        ),
        migrations.AddField(
            model_name='salle',
            name='processeur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Processeur'),
        ),
        migrations.AddField(
            model_name='salle',
            name='stockage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stockage'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs', to='reclamations.laboratoire', verbose_name='Laboratoire'),
        ),
        migrations.DeleteModel(
            name='Laboratoire',
        ),
    ]
