# Generated by Django 5.2 on 2025-05-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_salle_memoire_ram_salle_modele_postes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='ecran',
            field=models.CharField(blank=True, max_length=255, verbose_name='Écran'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='logiciels_installes',
            field=models.TextField(blank=True, verbose_name='Logiciels Installés'),
        ),
    ]
