# Generated by Django 4.2.19 on 2025-04-01 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pc', 'Ordinateur'), ('electrique', 'Équipement Électrique'), ('divers', 'Équipement Divers')], max_length=20)),
                ('identificateur', models.CharField(max_length=50, verbose_name="Identifiant de l'équipement")),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du Laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(choices=[('labo', 'Laboratoire'), ('salle', 'Salle'), ('bureau', 'Bureau')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('pc', 'Problèmes PC'), ('electrique', 'Problèmes Électriques'), ('divers', 'Problèmes Divers')], max_length=10, null=True, verbose_name='Catégorie')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description_generale', models.TextField(blank=True, null=True, verbose_name='Description générale')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamations.equipement')),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamations.laboratoire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('materiel', 'Problème Matériel'), ('logiciel', 'Problème Logiciel')], max_length=20)),
                ('description_probleme', models.TextField(blank=True, null=True)),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pc_details', to='reclamations.reclamation')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationElectrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('climatiseur', 'Climatiseur'), ('coupure_courant', 'Coupure de Courant'), ('autre', 'Autre')], max_length=20)),
                ('description_probleme', models.TextField(blank=True, null=True)),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electrique_details', to='reclamations.reclamation')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationDivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('tableau_blanc', 'Tableau Blanc'), ('video_projecteur', 'Vidéo Projecteur'), ('autre', 'Autre')], max_length=30)),
                ('description_probleme', models.TextField(blank=True, null=True)),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divers_details', to='reclamations.reclamation')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='reclamations.laboratoire'),
        ),
    ]
