# Generated by Django 4.2.19 on 2025-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='memoire_ram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mémoire RAM'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='modele_postes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modèle des postes'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='processeur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Processeur'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='stockage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stockage'),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
