# Generated by Django 4.2.19 on 2025-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_laboratoire_reclamationdivers_reclamationelectrique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='laboratoire',
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='lieu',
            field=models.CharField(choices=[('labo', 'Laboratoire'), ('salle', 'Salle'), ('bureau', 'Bureau')], max_length=20),
        ),
    ]
