# Generated by Django 5.2 on 2025-05-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_laboratoire_memoire_ram_laboratoire_modele_postes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={'verbose_name': 'Équipement', 'verbose_name_plural': 'Équipements'},
        ),
        migrations.AddField(
            model_name='reclamationdivers',
            name='equipement_specifique',
            field=models.CharField(blank=True, max_length=255, verbose_name="Équipement divers spécifique (si 'autre')"),
        ),
        migrations.AddField(
            model_name='reclamationelectrique',
            name='climatiseur_etat_specifique',
            field=models.CharField(blank=True, max_length=255, verbose_name="État climatiseur spécifique (si 'autre')"),
        ),
        migrations.AddField(
            model_name='reclamationpc',
            name='logiciel_specifique',
            field=models.CharField(blank=True, max_length=255, verbose_name="Logiciel spécifique (si 'autre')"),
        ),
        migrations.AddField(
            model_name='reclamationpc',
            name='materiel_specifique',
            field=models.CharField(blank=True, max_length=255, verbose_name="Matériel spécifique (si 'autre')"),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='identificateur',
            field=models.CharField(max_length=50, unique=True, verbose_name="Identifiant de l'équipement"),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_in_lab', to='reclamations.laboratoire'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='category',
            field=models.CharField(choices=[('pc', 'Problèmes PC'), ('electrique', 'Problèmes Électriques'), ('divers', 'Problèmes Divers')], max_length=10, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_equipement', to='reclamations.equipement'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_laboratoire', to='reclamations.laboratoire'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_in_bureau', to='reclamations.bureau'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_bureau', to='reclamations.bureau'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_in_salle', to='reclamations.salle'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_salle', to='reclamations.salle'),
        ),
    ]
