# Generated by Django 5.2 on 2025-05-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_bureau_salle_alter_equipement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='salle',
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={},
        ),
        migrations.RemoveField(
            model_name='reclamationdivers',
            name='equipement_specifique',
        ),
        migrations.RemoveField(
            model_name='reclamationelectrique',
            name='climatiseur_etat_specifique',
        ),
        migrations.RemoveField(
            model_name='reclamationpc',
            name='logiciel_specifique',
        ),
        migrations.RemoveField(
            model_name='reclamationpc',
            name='materiel_specifique',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='identificateur',
            field=models.CharField(max_length=50, verbose_name="Identifiant de l'équipement"),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='reclamations.laboratoire'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='category',
            field=models.CharField(blank=True, choices=[('pc', 'Problèmes PC'), ('electrique', 'Problèmes Électriques'), ('divers', 'Problèmes Divers')], max_length=10, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamations.equipement'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamations.laboratoire'),
        ),
        migrations.DeleteModel(
            name='Bureau',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
    ]
