# Generated by Django 5.2 on 2025-05-22 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0005_remove_equipement_bureau_remove_reclamation_bureau_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipement',
            unique_together={('laboratoire', 'identificateur')},
        ),
    ]
