# Generated by Django 5.2 on 2025-05-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0006_alter_equipement_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='equipement',
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=255, unique=True, verbose_name='Poste')),
                ('sn_inventaire', models.CharField(max_length=100, unique=True, verbose_name='S/N Inventaire')),
                ('logiciels_installes', models.TextField(blank=True, verbose_name='Logiciels Installés')),
                ('ecran', models.CharField(blank=True, max_length=255, verbose_name='Écran')),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs', to='reclamations.laboratoire', verbose_name='Laboratoire')),
            ],
            options={
                'verbose_name': 'PC',
                'verbose_name_plural': 'PCs',
                'db_table': 'gestion_pc',
            },
        ),
        migrations.AddField(
            model_name='reclamation',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='reclamations.pc'),
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
    ]
