# Generated by Django 4.2.19 on 2025-04-04 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclamations', '0002_reclamation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('action_effectuee', models.CharField(blank=True, choices=[('diagnostique', 'Diagnostique'), ('reparation', 'Réparation'), ('remplacement', 'Remplacement'), ('autre', 'Autre')], max_length=20, null=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='reclamations.reclamation')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions_assignees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
