# Generated by Django 4.2.19 on 2025-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intervention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='actions_entreprises',
            field=models.TextField(blank=True, help_text='Actions entreprises pour résoudre le problème', null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='analyse_cause',
            field=models.TextField(blank=True, help_text='Analyse et cause identifiée du problème', null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='fichier_joint',
            field=models.FileField(blank=True, help_text="Fichier joint à l'intervention (photos, diagnostics, etc.)", null=True, upload_to='interventions/'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='mots_cles',
            field=models.CharField(blank=True, help_text="Mots-clés pour faciliter la recherche d'interventions similaires", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='pieces_remplacees',
            field=models.TextField(blank=True, help_text="Liste des pièces remplacées pendant l'intervention", null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='probleme_constate',
            field=models.TextField(blank=True, help_text="Description détaillée du problème constaté lors de l'intervention", null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='recommandations',
            field=models.TextField(blank=True, help_text='Recommandations pour éviter que le problème ne se reproduise', null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='resultat_tests',
            field=models.TextField(blank=True, help_text="Résultats des tests effectués après l'intervention", null=True),
        ),
    ]
