# Generated by Django 5.2 on 2025-05-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intervention', '0002_intervention_actions_entreprises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='rapport_pdf',
            field=models.FileField(blank=True, help_text="Rapport PDF généré de l'intervention", null=True, upload_to='interventions/rapports/'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fichier_joint',
            field=models.FileField(blank=True, help_text="Fichier joint à l'intervention (photos, diagnostics, etc.)", null=True, upload_to='interventions/fichiers/'),
        ),
    ]
